services:
  app:
    image: adipatidhany/aksara:latest
    build: .
    env_file: .env
    environment:
      BOOKS_DIR: /app/books
      RESULTS_DIR: /app/results
      PYTHON_BIN: python3
      PARSER_SCRIPT: /app/parser/extract.py
    volumes:
      - ./books:/app/books
      - ./results:/app/results
    dns:
      - 8.8.8.8
      - 1.1.1.1
